DROP TABLE post;
CREATE TABLE Post (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    post_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);
